version: '3'

services:
    backend:
        build: .
        container_name: backend
        depends_on: 
          - database
        ports: 
          - 9090:9000
        command: >
          /bin/bash -c "
            echo 'waiting for mongo to start';
            echo 'Starting the server';
            npm run start"
        networks: 
          - backend-network
    database:
        image: mongo
        restart: on-failure
        container_name: emsolution-database
        ports: 
          - '5000:27017'
        networks: 
          - backend-network
        volumes: 
          - /home/sandeep/Desktop/react-native/projects/emsol/emsolution-backend/database:/data/db
    nginx: 
      image: nginx:mainline-alpine
      container_name: nginx
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
      networks:
        - backend-network
      ports:
        - 80:80
      depends_on: 
        - backend
        - database
networks:
  backend-network:      
